apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      serviceAccountName: my-serviceaccount-s3yaml
      containers:
      - name: go-app-demo
        image: shanchunyang0919/test:latest
        imagePullPolicy: IfNotPresent
    
